### ISSUE TITLE
Use the phpunit diff tool?

### ISSUE THREAD

**Issue by kilahm** [HackPack/HackUnit#13]
I kind of like the unified diff that phpUnit gives when an equality constraint is violated.  What do you think about including https://github.com/sebastianbergmann/diff as a dependency?

Perhaps long term we could convert that diff library to hack?

**Comment by kilahm** [comment]
@icambridge Are you still interested in developing the diff tool you started?  If not, I will close this issue and perhaps try to build something my self.

**Comment by icambridge** [comment]
@kilahm Well what features is it missing?

**Comment by kilahm** [comment]
@icambridge I'm not sure... were you done with it?  Would you like to make a PR integrating it into HackUnit?
