### ISSUE TITLE
Need maintainer

### ISSUE THREAD

**Issue by brianium** [HackPack/HackUnit#22]
@kilahm or @icambridge - I have not been investing too much time in Hack these days, as such I have not been keeping up with this project.

Would either of you be interested in taking it over? Anyone else you know?

**Comment by kilahm** [comment]
I would be willing to take over as maintainer.  I use Hack daily as part of my job and would love to have a maintained testing framework written in hack.

**Comment by brianium** [comment]
@kilahm you got it! adding you! thank you so much. excited to see where you take it
