### ISSUE TITLE
Support tests returning Awaitable<void>, run in parallel

### ISSUE THREAD

**Issue by fredemmott** [HackPack/HackUnit#31]
https://github.com/hhvm/user-documentation/blob/master/tests/InternalLinksTest.php is the best example I can think of for this - it can run against a remote server, so parralellization would be great.

**Comment by kilahm** [comment]
I will work on this for the next release.

**Comment by kilahm** [comment]
@fredemmott : take a look at [the async test](https://github.com/HackPack/HackUnit/blob/master/test/Test/Async.php) to see a sample. Setup and teardown aren't implemented yet.  Hope to get that done soon.

**Comment by fredemmott** [comment]
Awesome; just as a small nit, I'm not sure about having 'async' in the name, given http://docs.hhvm.com/hack/async/async-vs-awaitable

**Comment by kilahm** [comment]
I agree with you @fredemmott so I changed the name.
Also finished implementing suite and test setup/teardown methods as awaitable.
