### ISSUE TITLE
When  run the type checking, it will result in an error.

### ISSUE THREAD

**Issue by holyshared** [HackPack/HackUnit#33]
When  run the type checking, it will result in an error.

	vagrant@debian:~/shared/HackUnit$ hh_client
	src/Test/SuiteBuilder.php:44:40,45: The field line is undefined (Typing[4108])
	src/Test/SuiteBuilder.php:44:40,45: The field line is undefined (Typing[4108])
	src/Test/SuiteBuilder.php:44:40,45: The field line is undefined (Typing[4108])
	src/Util/Trace.php:21:59,64: Invalid argument (Typing[4140])
	  vendor/fredemmott/definition-finder/src/definitions/ScannedBase.php:23:34,47: The field 'line' is missing

The version of HHVM which tried is 3.12.0. 

	vagrant@debian:~/shared/HackUnit$ hhvm --version
	HipHop VM 3.12.0 (rel)
	Compiler: tags/HHVM-3.12.0-0-g440e6a096b2db8a449b9690a72f2f1792530e86a
	Repo schema: 033b8dedf4af99b892f2488b103a8d67a58ff816

**Comment by kilahm** [comment]
Looks like the line field for the SourcePosition shape was added after version 0.3.  When developing, I was using a branch from v1.1.  

I updated the dependency on definition-finder to `^1.0` and tagged HackUnit version 0.5.3.

Sorry for the confusion!
