### ISSUE TITLE
Support for hhvm-autoload

### ISSUE THREAD

**Issue by mhahn** [HackPack/HackUnit#52]
Would be great to add support for: https://github.com/fredemmott/hhvm-autoload

It seems like you could test for that as well as `composer.json`?

**Comment by GroovyCarrot** [comment]
A `--bootstrap=vendor/hh_autoload.php` flag would be nice, similar to PHPUnit?

**Comment by kilahm** [comment]
I would certainly welcome a PR!

**Comment by GroovyCarrot** [comment]
Here's basic hhvm/autoload support as an immediate solution: #54 
I also stumbled across this warning: #55

Can certainly look to flesh out the command line arguments when I get some time

**Comment by kilahm** [comment]
This is implemented in version 1.1.0.
