### ISSUE TITLE
Change "fredemmott/definition-finder" requirement to "facebook/definition-finder"

### ISSUE THREAD

**Issue by acrylic-origami** [HackPack/HackUnit#56]
Recently, the `definition-finder` package was migrated into the Facebook/HHVM organization when [Fred Emmott could no longer keep it under his personal account](https://www.facebook.com/groups/hhvm.general/permalink/772953629524699/), breaking dependencies.

The package can be found at [`facebook/definition-finder`](https://packagist.org/packages/facebook/definition-finder) ([Github](https://github.com/hhvm/definition-finder))

Its namespace has also changed from `\FredEmmott\DefinitionFinder` to `\Facebook\DefinitionFinder`.

**Comment by usox** [comment]
As I can see, ca370cb74b6995e93d5a4135e080710ed170b8c0 introduced this already in master 9 days ago

**Comment by acrylic-origami** [comment]
@usox Ha, didn't even notice that `develop` was the default branch! Thanks for pointing to the change.

**Comment by usox** [comment]
@acrylic-origami me too. A new patch version would be highly appreciated.

**Comment by kilahm** [comment]
Fixed in release 1.1.0.

Thanks all for bringing this to my attention.  I don't have much time for side projects anymore, but it's good to know this tool is still useful to folks.
