### ISSUE TITLE
Unbound name: Facebook\DefinitionFinder\FileParser

### ISSUE THREAD

**Issue by ghost** [HackPack/HackUnit#60]
Hi,

When I try to invoke hackunit, I got the following error:

```Catchable fatal error: Hack type error: Unbound name: Facebook\DefinitionFinder\FileParser (an object type) at /home/rducreux/Workspace/Hack/HackHTTP/vendor/hackpack/hackunit/src/Test/SuiteBuilder.php line 32```

I ran the following command:`hhvm vendor/hackpack/hackunit/bin/hackunit test/ClientTest.hh`

It seems to be an issue with autoloading.

I'm using HipHop VM 3.15.7 on Ubuntu 16.04.

**Comment by kilahm** [comment]
Thank you for your interest in HackUnit.  This was fixed in the most recent release.  Please update to version 1.1.0.
